In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import constants.constants as constants

In [3]:
print(constants.FILE_NAME)

/Users/gavi.vignes/Downloads/mlopsbootcamp/data/loan_approval_dataset.csv

In [11]:
df =pd.read_csv(constants.TEST_FILE)

In [12]:
df.head()

,Unnamed: 0,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1703,5,Graduate,No,5400000,19700000,20,423,6500000,10000000,15700000,7300000,0
1,1173,2,Graduate,No,5900000,14000000,8,599,4700000,9500000,17800000,6700000,1
2,308,3,Graduate,No,9600000,19900000,14,452,4200000,16200000,28500000,6600000,0
3,1322,2,Graduate,No,6200000,23400000,8,605,10000000,10800000,21800000,9200000,1
4,3271,3,Not Graduate,Yes,5800000,14100000,12,738,11700000,4400000,15400000,8400000,1

In [7]:
df.shape

(4269, 13)

In [8]:
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [9]:
df.isna().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [10]:
df.dtypes

loan_id                       int64
 no_of_dependents             int64
 education                   object
 self_employed               object
 income_annum                 int64
 loan_amount                  int64
 loan_term                    int64
 cibil_score                  int64
 residential_assets_value     int64
 commercial_assets_value      int64
 luxury_assets_value          int64
 bank_asset_value             int64
 loan_status                 object
dtype: object

In [11]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [25]:
df.columns = [c.strip() for c in df.columns]

In [26]:
df['loan_status'].value_counts()

loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [27]:
X = df.drop(columns=['loan_status'])
y = df['loan_status']

0     Approved
1     Rejected
2     Rejected
3     Rejected
4     Rejected
Name: loan_status, dtype: object

In [30]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
dtypes: int64(10), object(2)
memory usage: 400.3+ KB

In [33]:
# Apply domain knowledge as part of feature engineering

X['total_assets_value'] = X['residential_assets_value'] + X['commercial_assets_value'] + X['luxury_assets_value'] + X['bank_asset_value']

X.drop(columns=['residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'], inplace=True)

In [35]:
X['education'].unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [36]:
X['self_employed'].unique()

array([' No', ' Yes'], dtype=object)

In [37]:
y.unique()

array([' Approved', ' Rejected'], dtype=object)

In [38]:
X['education'] = X['education'].str.strip()
X['self_employed'] = X['self_employed'].str.strip()
y = y.str.strip()

In [39]:
X['education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [40]:
# Convert columns into categorical variables
X['education'] = np.where(X['education'] == 'Graduate', 1, 0)
X['self_employed'] = np.where(X['self_employed'] == 'Yes', 1, 0)

In [41]:
X['education'].unique()

array([1, 0])

In [42]:
X.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,1,2,1,0,9600000,29900000,12,778,50700000
1,2,0,0,1,4100000,12200000,8,417,17000000
2,3,3,1,0,9100000,29700000,20,506,57700000
3,4,3,1,0,8200000,30700000,8,467,52700000
4,5,5,0,1,9800000,24200000,20,382,55000000

In [43]:
y.head()

0    Approved
1    Rejected
2    Rejected
3    Rejected
4    Rejected
Name: loan_status, dtype: object

In [44]:
y = np.where(y == 'Approved', 1, 0)

In [47]:
y

array([1, 0, 0, ..., 0, 1, 1])

In [48]:
# Log transformation
log_cols = ['income_annum', 'loan_amount', 'total_assets_value']
X[log_cols] = np.log(X[log_cols])

In [50]:
X.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,1,2,1,0,16.077274,17.213369,12,778,17.741436
1,2,0,0,1,15.226498,16.316947,8,417,16.648724
2,3,3,1,0,16.023785,17.206658,20,506,17.870768
3,4,3,1,0,15.919645,17.239773,8,467,17.780126
4,5,5,0,1,16.097893,17.001863,20,382,17.822844

In [51]:
X.drop(columns=['loan_id'], inplace=True)

In [53]:
# Building the model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [54]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

/Users/gavi.vignes/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [55]:
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")

Accuracy: 0.9008587041373927

# Notebook to Production

In [57]:
# Local environment to cloud environment to deploy at scale virtual machine

# requirements.txt

In [58]:
import joblib
joblib.dump(lr, 'loan_approval_model.pkl')

['loan_approval_model.pkl']

In [59]:
final_model = joblib.load('loan_approval_model.pkl')
final_model.intercept_, final_model.coef_

(array([-1.12394658]),
 array([[-0.03247311,  0.00371268,  0.08231784, -1.22901774,  1.39479423,
         -0.13442597,  0.02371691, -0.8135648 ]]))

In [61]:
lr.intercept_, lr.coef_

(array([-1.12394658]),
 array([[-0.03247311,  0.00371268,  0.08231784, -1.22901774,  1.39479423,
         -0.13442597,  0.02371691, -0.8135648 ]]))

### Packaging & Moduling Python files

In [5]:
from src.f1 import f1

f1()

f1